<?php
/**
 * @category   Commcenter
 * @package    Commcenter_Preregistro
 * @author     yurirneves@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Commcenter\Preregistro\Controller\Index;

use Magento\Framework\App\Action\Context;
use Commcenter\Preregistro\Model\PreregistroFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Preregistro
     */
    protected $_preregistro;

    public function __construct(
		Context $context,
        PreregistroFactory $preregistro
    ) {
        $this->_preregistro = $preregistro;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$preregistro = $this->_preregistro->create();
        $preregistro->setData($data);
        if($preregistro->save()){
            $this->messageManager->addSuccessMessage(__('Obrigado! Registro salvo com sucesso'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('/');
        return $resultRedirect;
    }
}
