
<style>
.tooltip {
    display:inline-block;
    position:relative;
    text-align:left;
}

.tooltip .top {
    min-width: 200px;
    top: -11px;
    left: 50%;
    transform: translate(-50%, -100%);
    padding: 15px;
    color: #444444;
    background-color: #EEEEEE;
    font-weight: normal;
    font-size: 10px;
    line-height: 7px;
    border-radius: 5px;
    position: absolute;
    z-index: 99999999;
    box-sizing: border-box;
    box-shadow: 0 1px 2px rgba(0,0,0,0.5);
    visibility: hidden;
    opacity: 0;
    transition: opacity 0.4s;
}

.tooltip:hover .top {
    visibility:visible; opacity:1;
}

.tooltip .top i {
    position:absolute;
    top:100%;
    left:50%;
    margin-left:-12px;
    width:24px;
    height:12px;
    overflow:hidden;
}

.tooltip .top i::after {
    content:'';
    position:absolute;
    width:12px;
    height:12px;
    left:50%;
    transform:translate(-50%,-50%) rotate(45deg);
    background-color:#EEEEEE;
    box-shadow:0 1px 8px rgba(0,0,0,0.5);
}

.price-box.price-final_price {
    margin: 0px;
}
</style>
