<!--
 /**
 * Mestre Magento
 * www.modulomagento.com.br
 *
 * LICENÇA DE USO
 * Este arquivo está sujeito ao EULA (contrato de licença para usuário final).
 * @copyright Copyright (c) Mestre Magento. ( https://www.modulomagento.com.br/ )
 * @license   https://www.modulomagento.com.br/Mestre-Magento-Licenca.txt
 *
 * ##############################################################################
 * #																			#
 * #  Nós programadores nos dedicamos muito, da mesma forma que você, então		#
 * #  valorize sua profissão e não aceite usar esse módulo de forma ilícita.	#
 * #  Denuncie anônimamente a empresa que utilizar esse módulo de forma ilegal.	#
 * #  Estamos abertos a parcerias com desenvolvedores ;)						#
 * #																			#
 * ##############################################################################
 *
 */
-->
<script type="text/javascript">
require([
    'jquery'
], function(jQuery){
    (function($) {
        $('#sync_from_ebay-import_pro_from_ebay').click(function(e){
            $('#sync_from_ebay .action-toggle').trigger('click');
            $('.admin__data-correios-loading-mask,.admin__menu-overlay').show();

        	var subcat=$(this);
        	e.preventDefault();
            $.ajax({
                url: "<?php echo $block->getUrl('*/*/import')?>",
                data: {form_key: window.FORM_KEY},
                type: 'POST',
                dataType:'JSON',
                success: function(ebayPro){
                    if(ebayPro.error_msg==false){
                        var msg='Total '+ebayPro.data.length +' products imported in your store from eBay run profiler for create these product in your store';
                        $('<div />').html(msg)
                            .modal({
                                title: $.mage.__('Attention'),
                                autoOpen: true,
                                buttons: [{
                                 text: 'OK',
                                    attr: {
                                        'data-action': 'cancel'
                                    },
                                    'class': 'action-primary',
                                    click: function() {
                                            this.closeModal();
                                        }
                                }]
                            });
                    }else{
                        $('<div />').html(ebayPro.error_msg)
                            .modal({
                                title: $.mage.__('Attention'),
                                autoOpen: true,
                                buttons: [{
                                 text: 'OK',
                                    attr: {
                                        'data-action': 'cancel'
                                    },
                                    'class': 'action-primary',
                                    click: function() {
                                            this.closeModal();
                                        }
                                }]
                            });
                    }
                },
                error: function(error){
                	console.log(error);
                }
            }).done(function(){
            	$('.admin__data-correios-loading-mask,.admin__menu-overlay').hide();
            });
        });
        
        $('#sync_from_ebay-profiler_for_create_pro').click(function(e) {
            $('#sync_from_ebay .action-toggle').trigger('click');
            window.open("<?php echo $this->getUrl('mpebaymagentoconnect/products/profiler')?>");
        });

        $('#sync_from_ebay-import_pro_to_ebay').click(function(e) {
            $('#sync_from_ebay .action-toggle').trigger('click');
            window.open("<?php echo $this->getUrl('mpebaymagentoconnect/products/importinebay')?>");
        });
    })(jQuery);
});
</script>