<!--
 /**
 * Mestre Magento
 * www.modulomagento.com.br
 *
 * LICENÇA DE USO
 * Este arquivo está sujeito ao EULA (contrato de licença para usuário final).
 * @copyright Copyright (c) Mestre Magento. ( https://www.modulomagento.com.br/ )
 * @license   https://www.modulomagento.com.br/Mestre-Magento-Licenca.txt
 *
 * ##############################################################################
 * #																			#
 * #  Nós programadores nos dedicamos muito, da mesma forma que você, então		#
 * #  valorize sua profissão e não aceite usar esse módulo de forma ilícita.	#
 * #  Denuncie anônimamente a empresa que utilizar esse módulo de forma ilegal.	#
 * #  Estamos abertos a parcerias com desenvolvedores ;)						#
 * #																			#
 * ##############################################################################
 *
 */
-->
<div  data-area-active="true">
    <div class="fieldset-wrapper"  data-level="0" data-index="customer">


        <div class="fieldset-wrapper-title"  tabindex="-1">

            <strong  class="title">
                <span >Inclusão de pedido </span>
            </strong>
        </div>

        <div class="admin__fieldset-wrapper-content _hide" >
            <fieldset class="admin__fieldset" >
                <div class="admin__field _required _disabled"  data-index="website_id">


<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

$order_id = $this->getRequest()->getParam('order_id');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('\Magento\Sales\Model\Order')->load($order_id);


$additionalInformation = $order->getPayment()->getAdditionalInformation();


if(isset($additionalInformation['shipmentIdCorreios']) && $additionalInformation['shipmentIdCorreios']):

  $shipmentIdCorreios = $additionalInformation['shipmentIdCorreios'];
?>


    <div class="col-md-12">
        <h3 style="    margin-left: 55px;">Codigo de Rastreio: <?=$additionalInformation['shipmentIdCorreios']?>
            <button type="submit" onclick="sendPedidoCorreios()" class="btn btn-primary">Cancelar</button>
    </div>


    <script>
        var order_id = "<?=$order_id?>";
        function sendPedidoCorreios() {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    alert(this.responseText);
                    location.reload();
                }
            };
            var hash = '{"tipo":"2","shipmentId":"<?=$shipmentIdCorreios?>","order_id":"'+order_id+'"}';
            xmlhttp.open("GET", "<?=$baseUrl?>rest/all/V1/mestremage-correios/sendpediocorreios?hash=" + encodeURI(hash), true);
            xmlhttp.send();

        }
    </script>
<?php else: ?>

                                        <div class="admin__field"  data-index="prefix">
                                            <div class="admin__field-label" ><label  for="danfeCte"><span >Numero da DANFE ou CTE:</span></label></div>
                                            <div class="admin__field-control" ><input class="admin__control-text" type="text"  id="danfeCte" maxlength="255"></div>
                                        </div>

                                        <div class="admin__field"  data-index="prefix">
                                            <div class="admin__field-label" ><label  for="nrDoc"><span >Numero do documento:</span></label></div>
                                            <div class="admin__field-control" ><input class="admin__control-text" type="text"  aria-describedby="notice-Y9TU3HU" id="nrDoc" maxlength="255"></div>
                                        </div>

                                        <div class="admin__field"  data-index="prefix">
                                            <div class="admin__field-label" ><label  for="serie"><span >Serie do documento:</span></label></div>
                                            <div class="admin__field-control" >
                                                <select id="serie" name="serie">
                                                    <option value="0">0</option>
                                                    <option value="1">1</option>
                                                </select></div>
                                        </div>

                                        <div class="admin__field"  data-index="prefix">
                                            <div class="admin__field-label" ><label  for="cfop"><span >CFOP da Nfe:</span></label></div>
                                            <div class="admin__field-control" ><input class="admin__control-text" type="text"  aria-describedby="notice-Y9TU3HU" id="cfop" maxlength="255"></div>
                                        </div>

                                        <div class="admin__field"  data-index="prefix">
                                            <div class="admin__field-label" ><label  for="tpDocumento"><span >Tipo do documento fiscal:</span></label></div>
                                            <div class="admin__field-control" >
                                                  <select id="tpDocumento" name="tpDocumento">
                                                   <option value="0">Declaracao</option>
                                                   <option value="1">NF</option>
                                                   <option value="2">NFE</option>
                                                   <option value="4">CTE</option>
                                               </select>
                                            </div>
                                        </div>


    <button type="submit" onclick="sendPedidoCorreios()" class="btn btn-primary">Enviar</button>




<script>
    var order_id = "<?=$order_id?>";
    function sendPedidoCorreios() {
        var danfeCte = document.getElementById('danfeCte').value;
        var nrDoc = document.getElementById('nrDoc').value;
        var serie = document.getElementById('serie').value;
        var cfop = document.getElementById('cfop').value;
        var tpDocumento = document.getElementById('tpDocumento').value;
        var tipo = 1;

        if(danfeCte && nrDoc && serie && cfop){
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    alert(this.responseText);
                    location.reload();
                }
            };

            var hash = '{"danfeCte":"'+danfeCte+'","nrDoc":"'+nrDoc+'","serie":"'+serie+'","tipo":"'+tipo+'","cfop":"'+cfop+'","order_id":"'+order_id+'","tpDocumento":"'+tpDocumento+'"}';
            xmlhttp.open("GET", "<?=$baseUrl?>rest/all/V1/mestremage-correios/sendpediocorreios?hash=" + encodeURI(hash), true);
            xmlhttp.send();
        }else{
            alert('erro');
        }


    }
</script>
<?php endif; ?>


        </div>
    </fieldset>
    </div>
    </div>
</div>
<style>
    .admin__field-control .admin__control-text {
        width: 30%;
        margin-left: 10px;
    }
    .admin__field:not(.admin__field-option) > .admin__field-label {
        float: left;
        margin-left: 40px;
        width: 208px;
        text-align: left;
    }
    div#Pedido_Correios button.btn.btn-primary {
        margin: 21px 44%;
        display: flex;
    }
    div#Pedido_Correios  select {
        -webkit-appearance: none;
        background-color: #ffffff;
        border: 1px solid #adadad;
        border-radius: 1px;
        box-shadow: none;
        color: #303030;
        font-size: 1.4rem;
        font-weight: 400;
        height: auto;
        line-height: 1.36;
        padding: 0.6rem 1rem 0.6rem;
        transition: border-color 0.1s linear;
        vertical-align: baseline;
        margin-left: 10px;
    }

</style>