<?php

ini_set('memory_limit', '1024M');

use Magento\Framework\App\Bootstrap;

require __DIR__ . '/../app/bootstrap.php';

$bootstrap = Bootstrap::create(BP, $_SERVER);
$obj = $bootstrap->getObjectManager();

$state = $obj->get('Magento\Framework\App\State');
$state->setAreaCode('frontend');

$customerSession = $obj->get('Magento\Customer\Model\Session');
$customerRepository = $obj->get('Magento\Customer\Api\CustomerRepositoryInterface');

if (isset($_REQUEST['atr_lbl']) && isset($_REQUEST['atr_value'])) {
    if ($customerSession->isLoggedIn()) {
        $customer = $customerRepository->getById($customerSession->getCustomer()->getId());
        $customer->setCustomAttribute($_REQUEST['atr_lbl'], $_REQUEST['atr_value']);
        $customerRepository->save($customer);
    }
} else {
    $collection = $obj->create('Magento\Customer\Model\ResourceModel\Customer\Collection')
        ->addAttributeToSelect('taxvat')
        ->load();

    $taxvat = [];
    foreach ($collection as $item) {
        $taxvat[] = soNumero($item->getTaxvat());
    }

    $retorno = 0;

    if (isset($_REQUEST['taxvat'])) {
        $inputTaxvat = soNumero($_REQUEST['taxvat']);

        if (in_array($inputTaxvat, $taxvat)) {
            $retorno = 1;
            if ($customerSession->isLoggedIn()) {
                if (soNumero($customerSession->getCustomer()->getTaxvat()) == $inputTaxvat) {
                    $retorno = 0;
                }
            }
        } else {
            if ($customerSession->isLoggedIn()) {
                if (soNumero($customerSession->getCustomer()->getTaxvat()) != $inputTaxvat) {
                    $customer = $customerRepository->getById($customerSession->getCustomer()->getId());
                    $customer->setTaxvat($_REQUEST['taxvat']);
                    $customerRepository->save($customer);
                }
            }
        }
    }

    echo $retorno;
}

function soNumero($str)
{
    return $str ? preg_replace("/[^0-9]/", "", $str) : '';
}
