<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
$scopeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$ModulesManagement = $objectManager->get('\MestreMage\Core\Model\ModulesManagement');

$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

$inscricao_estadual = "";
$razao_social = "";
$taxvat = "";
$tipo_pessoa = 1;
if($customerSession->isLoggedIn()) {
	$razao_social = $customerSession->getCustomer()->getRazaoSocial();
	$inscricao_estadual = $customerSession->getCustomer()->getInscricaoEstadual();
	$taxvat = $customerSession->getCustomer()->getTaxvat();
}

$razao_social_config = $scopeConfig->getValue("mmcpfcnpj/loja/razao_social", $storeScope);
$inscricao_estadual_config = $scopeConfig->getValue("mmcpfcnpj/loja/inscricao_estadual", $storeScope);
$valid_inscricao_estadual = $scopeConfig->getValue("mmcpfcnpj/loja/valid_inscricao_estadual", $storeScope);

if (strlen(preg_replace("/[^0-9]/", "", $taxvat)) > 11) {
	$tipo_pessoa = 2;
}

?>
<?php //$this->setShowAddressFields(true); ?>
<?php //if($this->getShowAddressFields()): ?>
<?php if($scopeConfig->getValue("mmcpfcnpj/geral/ativarmodulo", $storeScope) && $ModulesManagement->testModule($scopeConfig->getValue(\base64_decode('bW1jcGZjbnBqL2dlcmFsL2FjdGl2ZV9oYXNo'), $storeScope),'MestreMage_CpfCnpj')): ?>
<script>
  var yapay_credit_card = "<?=$scopeConfig->getValue('payment/yapay_credit_card/active', $storeScope)?>";
	var htmlCheck,htmlFisica,htmlJuridica;

	htmlCheck = '	<div class="cont_pessoa">';
	htmlCheck += '<label class="checkbox-inline"><input type="radio" id="pessoa_fisica" class="cls_tipo_pessoa" name="ck_tipo_pessoa" value="1" <?php echo ( $tipo_pessoa == 1 ? "checked" : "" ); ?> >Pessoa Física</label>';
	htmlCheck += '<label class="checkbox-inline"><input type="radio" id="pessoa_juridic" class="cls_tipo_pessoa" name="ck_tipo_pessoa" value="2" <?php echo ( $tipo_pessoa == 2 ? "checked" : "" ); ?>>Pessoa Jurídica</label>';
	htmlCheck += '</div>';
	htmlCheck += '<div class="cont_check_mm"></div>';

	htmlFisica = '<label class="label" id="lbl_pessoa_fisica" for="taxvat"><span><?=__('CPF')?></span></label>';
	htmlFisica += '<div class="control">';
	htmlFisica += '	<input type="text" id="taxvat" inputmode="numeric" onchange="buscarTaxVat(this)" onkeyup="mascaraMutuario(this,cpfCnpj)" name="taxvat" value="" title="<?=__('CPF')?>" class="input-text " data-validate="{required:true}" autocomplete="off" aria-required="true">';
	htmlFisica += '	</div>';
	htmlFisica += '	<input type="hidden" name="tipo_pessoa" value="1">';



	htmlJuridica = '<label class="label" id="lbl_pessoa_juridica" for="taxvat"><span><?=__('CNPJ')?></span></label>';
	htmlJuridica += '<div class="control">';
	htmlJuridica += '	<input type="text" id="taxvat" inputmode="numeric" onchange="buscarTaxVat(this)" onkeyup="mascaraMutuario(this,cpfCnpj)" name="taxvat" value="" title="<?=__('CNPJ')?>" class="input-text " data-validate="{required:true}" autocomplete="off" aria-required="true">';
	htmlJuridica += '</div>';
	htmlJuridica += '<input type="hidden" name="tipo_pessoa" value="2">';

	if(yapay_credit_card){
		htmlJuridica = '<label class="label" id="lbl_pessoa_fisica" for="taxvat"><span><?=__('CPF')?></span></label>';
		htmlJuridica += '<div class="control">';
		htmlJuridica += '	<input type="text" id="taxvat" inputmode="numeric" onchange="buscarTaxVat(this)" onkeyup="mascaraMutuario(this,cpfCnpj)" name="taxvat" value="" title="<?=__('CPF')?>" class="input-text " data-validate="{required:true}" autocomplete="off" aria-required="true">';
		htmlJuridica += '	</div>';
		htmlJuridica += '	<input type="hidden" name="tipo_pessoa" value="1">';

	}

	<?php if($razao_social_config): ?>
	htmlJuridica += '<label class="label razao_social" for="razao_social"><span><?=__('Razão Social')?></span></label>';
	htmlJuridica += '<div class="control">';
	htmlJuridica += '	<input type="text" id="razao_social" name="razao_social" value="" title="<?=__('Razão Social')?>" class="input-text " <?php if($razao_social_config == 2): ?> data-validate="{required:true}" autocomplete="off" aria-required="true" 	<?php endif; ?> >';
	htmlJuridica += '</div>';
	<?php endif; ?>

	<?php if($inscricao_estadual_config): ?>
	htmlJuridica += '<label class="label inscricao_estadual" for="inscricao_estadual"><span><?=__('Inscrição Estadual')?></span></label>';
	htmlJuridica += '<div class="control">';
	htmlJuridica += '	<input type="text" id="inscricao_estadual"  onblur="CheckIE()" inputmode="numeric" name="inscricao_estadual" value="" title="<?=__('Inscrição Estadual')?>" class="input-text "  <?php if($inscricao_estadual_config == 2): ?>  data-validate="{required:true}" autocomplete="off" aria-required="true" 	<?php endif; ?> >';
	htmlJuridica += '</div>';
	<?php endif; ?>

var tipo_pessoa = "<?=$tipo_pessoa?>";
var razao_social = "<?=$razao_social?>";
var inscricao_estadual = "<?=$inscricao_estadual?>";
var taxvat = "<?=$taxvat?>";
	require([
		"jquery",
		"jquery/ui"
	], function($){
		if(yapay_credit_card){
			$(".taxvat").html('<div class="cont_check_mm"></div>');
			$(".cont_check_mm").html(htmlJuridica);
			$("#taxvat").attr('maxlength','14');
			$("#cnpj").attr('maxlength','18');
			$("fieldset.fieldset.create.account .field.promotion_code.required:nth-child(3)").hide();

			$("#taxvat").keyup(function() {
				$('.field.promotion_code input#cpf').val($(this).val());
			});

			$("#cnpj").keyup(function() {
			
				v=$(this).val().replace(/\D/g,"");
				if (v.length > 0 && v.length <= 11) {
					//CPF
					v=v.replace(/(\d{3})(\d)/,"$1.$2");
					v=v.replace(/(\d{3})(\d)/,"$1.$2");
					v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2")
				} else {
					//CNPJ
					v=v.replace(/^(\d{2})(\d)/,"$1.$2");
					v=v.replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3");
					v=v.replace(/\.(\d{3})(\d)/,".$1/$2");
					v=v.replace(/(\d{4})(\d)/,"$1-$2");
				}
				$(this).val(v);

			});

		}else{
			
		$(".taxvat").html(htmlCheck);
		$(".cont_check_mm").html(htmlFisica);

		$("#taxvat").attr('maxlength','14');
		if(tipo_pessoa == 2){
			$(".cont_check_mm").html(htmlJuridica);
			$("#taxvat").attr('maxlength','18');
		}


		$('#inscricao_estadual').val(inscricao_estadual);
		$('#razao_social').val(razao_social);

		$('#taxvat').val(taxvat);
		$('input.cls_tipo_pessoa').change(function() {
			if(this.checked) {
				if(this.value == 1){
					$(".cont_check_mm").html(htmlFisica);
					$("input#taxvat").attr('value',(tipo_pessoa == this.value ? taxvat : '' )).attr('maxlength','14');
				}else if(this.value == 2){
					$(".cont_check_mm").html(htmlJuridica);
					$("input#taxvat").attr('value',(tipo_pessoa == this.value ? taxvat : '' )).attr('maxlength','18');
				}
			}
			$('#inscricao_estadual').val(inscricao_estadual);
			$('#razao_social').val(razao_social);

		});
		}



	});
</script>

<script>
	function mascaraMutuario(o,f){
		v_obj=o;
		v_fun=f;
		setTimeout('execmascara()',1)
	}

	function execmascara(){
		v_obj.value=v_fun(v_obj.value)
	}

	function cpfCnpj(v){
		v=v.replace(/\D/g,"");
		if (v.length > 0 && v.length <= 11) {
			//CPF
			v=v.replace(/(\d{3})(\d)/,"$1.$2");
			v=v.replace(/(\d{3})(\d)/,"$1.$2");
			v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2")
		} else {
			//CNPJ
			v=v.replace(/^(\d{2})(\d)/,"$1.$2");
			v=v.replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3");
			v=v.replace(/\.(\d{3})(\d)/,".$1/$2");
			v=v.replace(/(\d{4})(\d)/,"$1-$2");
		}
		return v
	}


	function buscarTaxVat(val) {
		validaCampo(val.value);
		<?php if($scopeConfig->getValue("mmcpfcnpj/loja/taxvat_unico", $storeScope)): ?>
		if(validaCampo(val.value)) {
			var xmlhttp = new XMLHttpRequest();
			xmlhttp.onreadystatechange = function () {
				if (this.readyState == 4 && this.status == 200) {

					var taxvat = document.querySelector('#taxvat');


					var labelTipoDoc = '';
					if(document.querySelector('#pessoa_fisica')){
						if (document.querySelector('#pessoa_fisica').checked) {
							labelTipoDoc = 'CPF';
						} else {
							labelTipoDoc = 'CNPJ';
						}
					}else{
						labelTipoDoc = 'CPF';
					}


					if (this.responseText == 1) {

						if (!document.querySelector('.cpf-cnpj-mm')) {
							taxvat.insertAdjacentHTML('afterend', '<div class="field-error cpf-cnpj-mm" data-bind="attr: { id: element.errorId }" generated="true" id="cpf-cnpj-mm"><span data-bind="text: element.error">' + labelTipoDoc + ' já cadastrado, <a href="<?php echo  $baseUrl ?>customer/account/login/"> clique aqui para se logar </a> </span></div>');
						}
						taxvat.style.border = "1px solid #ed8380";
						document.querySelector('.cpf-cnpj-mm').style.display = "Block";
						document.querySelector('.actions-toolbar > .primary .action:last-child').style.display = "none";
					} else {
						if (document.querySelector('.cpf-cnpj-mm'))
							document.querySelector('.cpf-cnpj-mm').style.display = "none";

						document.querySelector('.actions-toolbar > .primary .action:last-child').style.display = "Block";
						taxvat.style.border = "1px solid #c2c2c2";
					}


				}
			};
			xmlhttp.open("GET", "<?php echo  $baseUrl ?>mestremage_cpfcnpj?taxvat=" + val.value + "&_=" + Date.now(), true);
			xmlhttp.send();
		}
<?php endif; ?>
	}


</script>
<style>
	.cont_check_mm label.label {
		font-weight: 600;
		margin: 0 0 8px;
		display: inline-block;
	}
	<?php if($razao_social_config == 2): ?>
	.razao_social:after {
		content: '*';
		color: #e02b27;
		font-size: 1.2rem;
		margin: 0 0 0 5px;
	}
	<?php endif; ?>
	<?php if($inscricao_estadual_config == 2): ?>
	.inscricao_estadual:after {
		content: '*';
		color: #e02b27;
		font-size: 1.2rem;
		margin: 0 0 0 5px;
	}
	<?php endif; ?>

	.cont_check_mm .control {
		margin: 0 0 20px;
	}
	.cont_pessoa > label {
		margin-right: 20px;
	}
	.field.password .control {
		width: 100%;
	}
</style>
<?php endif; ?>

<script>
	function validaCampo(object) {
		object = object.replace(/[^\d]+/g,'');
        if(object.indexOf("1111111111")!=-1 ||
            object.indexOf("2222222222")!=-1 ||
            object.indexOf("3333333333")!=-1 ||
            object.indexOf("4444444444")!=-1 ||
            object.indexOf("5555555555")!=-1 ||
            object.indexOf("6666666666")!=-1 ||
            object.indexOf("7777777777")!=-1 ||
            object.indexOf("8888888888")!=-1 ||
            object.indexOf("9999999999")!=-1) {
			errorReturn();
			return false;
		}


		if (object.length <= 12) {

			var pessoa_juridic = false;
			if(document.querySelector('#pessoa_juridic')){
				pessoa_juridic = document.querySelector('#pessoa_juridic').checked;
			}
			if(pessoa_juridic){
				errorReturn();
				return false;
			}else{
				sucessReturn();
				return ValidarCPF(object)
			}
		

		} else {
			return ValidarCNPJ(object)
		}
	}
	//valida o CPF digitado
	function ValidarCPF(Objcpf) {
		var cpf = Objcpf;
		var exp = /\.|\-/g;
		cpf = cpf.toString().replace(exp, "");


		if (VerificaCPF(cpf)) {
			sucessReturn();
		} else {
			errorReturn();
		}
		return VerificaCPF(cpf);
	}
	//valida o CNPJ digitado
	function ValidarCNPJ(ObjCnpj) {

		var cnpj = ObjCnpj;
		var valida = new Array(6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2);
		var dig1 = new Number;
		var dig2 = new Number;

		exp = /\.|\-|\//g;
		cnpj = cnpj.toString().replace(exp, "");
		var digito = new Number(eval(cnpj.charAt(12) + cnpj.charAt(13)));

		for (i = 0; i < valida.length; i++) {
			dig1 += (i > 0 ? (cnpj.charAt(i - 1) * valida[i]) : 0);
			dig2 += cnpj.charAt(i) * valida[i];
		}
		dig1 = (((dig1 % 11) < 2) ? 0 : (11 - (dig1 % 11)));
		dig2 = (((dig2 % 11) < 2) ? 0 : (11 - (dig2 % 11)));

		if (((dig1 * 10) + dig2) != digito) {
			errorReturn();
			return false;
		} else {
			sucessReturn();
			return true;
		}

	}

	function sucessReturn(){
		var taxvat = document.querySelector('#taxvat');
		if(document.querySelector('.cpf-cnpj-mm-val')){
			document.querySelector('.cpf-cnpj-mm-val').style.display = "none";
		}


		document.querySelector('.actions-toolbar > .primary .action:last-child').disabled = false;
		taxvat.style.border = "1px solid #c2c2c2";
	}
	function errorReturn(){
		var taxvat = document.querySelector('#taxvat');
		if (!document.querySelector('.cpf-cnpj-mm-val')) {
			taxvat.insertAdjacentHTML('afterend', '<div class="field-error cpf-cnpj-mm-val" data-bind="attr: { id: element.errorId }" generated="true" id="cpf-cnpj-mm-val"><span data-bind="text: element.error"> CPF/CNPJ Inválido </span></div>');
		}
		taxvat.value = "";
		taxvat.style.border = "1px solid #ed8380";
		document.querySelector('.cpf-cnpj-mm-val').style.display = "Block";
		document.querySelector('.actions-toolbar > .primary .action:last-child').disabled = true;
	}

	function VerificaCPF(strCpf) {

		var soma;
		var resto;
		soma = 0;
		if (strCpf == "00000000000") {
			return false;
		}

		for (i = 1; i <= 9; i++) {
			soma = soma + parseInt(strCpf.substring(i - 1, i)) * (11 - i);
		}

		resto = soma % 11;

		if (resto == 10 || resto == 11 || resto < 2) {
			resto = 0;
		} else {
			resto = 11 - resto;
		}

		if (resto != parseInt(strCpf.substring(9, 10))) {
			return validarCpf2(strCpf);
		}

		soma = 0;

		for (i = 1; i <= 10; i++) {
			soma = soma + parseInt(strCpf.substring(i - 1, i)) * (12 - i);
		}
		resto = soma % 11;

		if (resto == 10 || resto == 11 || resto < 2) {
			resto = 0;
		} else {
			resto = 11 - resto;
		}

		if (resto != parseInt(strCpf.substring(10, 11))) {
			return validarCpf2(strCpf);
		}

		return true;
	}


	function validarCpf2(strCPF) {
		var Soma;
		var Resto;
		Soma = 0;
		if (strCPF == "00000000000") return false;

		for (i=1; i<=9; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (11 - i);
		Resto = (Soma * 10) % 11;

		if ((Resto == 10) || (Resto == 11))  Resto = 0;
		if (Resto != parseInt(strCPF.substring(9, 10)) ) return false;

		Soma = 0;
		for (i = 1; i <= 10; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (12 - i);
		Resto = (Soma * 10) % 11;

		if ((Resto == 10) || (Resto == 11))  Resto = 0;
		if (Resto != parseInt(strCPF.substring(10, 11) ) ) return false;
		return true;
	}


function CheckIE() {
   ie = document.getElementById('inscricao_estadual').value;

   if (ie) {
        var inscricao_estadual =  document.querySelector('#inscricao_estadual');

        if (isValidIe(ie)) {
            if(document.querySelector('.inscricao-estadual-mm-val')){
                document.querySelector('.inscricao-estadual-mm-val').style.display = "none";
            }

            inscricao_estadual.style.border = "1px solid #c2c2c2";
        } else {           
            inscricao_estadual.style.border = "1px solid #ed8380";
            if (!document.querySelector('.inscricao-estadual-mm-val')) {
                inscricao_estadual.insertAdjacentHTML('afterend', '<div class="field-error inscricao-estadual-mm-val" data-bind="attr: { id: element.errorId }" generated="true" id="cpf-cnpj-mm-val"><span data-bind="text: element.error"> Inscrição Estadual Inválida </span></div>');
            }

            document.querySelector('.inscricao-estadual-mm-val').style.display = "Block";
        }
    }

}

function isValidIe(ie) {
    let uf = "AL,AP,AM,BA,CE,DF,ES,GO,MA,MT,MS,MG,PA,PB,PR,PE,PI,RJ,RN,RS,RO,RR,SC,SP,SE,TO";
    const estados = uf.split(",");

    var valid = 0;
    estados.forEach(function(uf){
        if (validIe(uf, ie)) {
         valid++;
        }
    });

    return valid;
}

function validIe(estado, ie) {

   ie = ie.replace(/\./g, "");
   ie = ie.replace(/\\/g, "");
   ie = ie.replace(/\-/g, "");
   ie = ie.replace(/\//g, "");

   if ( ie == "ISENTO" )
      return true;

   switch(estado)
   {

   case "AC":
   
        if (ie.length != 13)
           return false;
        var b = 4, soma = 0;
        for (var i=0; i<=10; i++)
        {
            soma += parseInt(ie.charAt(i)) * b;
            --b;
            if (b == 1)
			   b = 9;
        }
        dig = 11 - (soma % 11);
        if (dig >= 10)
		   dig = 0;
        if (dig != parseInt(ie.charAt(11)))
		   return false;
        b = 5;
        soma = 0;
        for (var i=0; i<=11; i++)
        {
            soma += parseInt(ie.charAt(i)) * b;
            --b;
            if (b == 1)
			   b = 9;
        }
        dig = 11 - (soma % 11);
        if (dig >= 10)
		   dig = 0;
        return (dig == parseInt(ie.charAt(12)));
        break;
	   
   case "AL":
   
        if (ie.length != 9)
           return false;
        var b = 9, soma = 0;
        for (var i=0; i<=7; i++)
        {
            soma += parseInt(ie.charAt(i)) * b;
            --b;
        }
        soma *= 10;
        dig = soma - (Math.floor(soma / 11) * 11);
        if (dig == 10) 
		   dig = 0;
        return (dig == parseInt(ie.charAt(8)));
        break;

   case "AM":

        if (ie.length != 9)
           return false;
        var b = 9, soma = 0;
        for (var i=0; i<=7; i++)
        {
            soma += parseInt(ie.charAt(i)) * b;
            b--;
        }
        if (soma < 11)
		{
		   dig = 11 - soma;
        }
        else
        {
           i = soma % 11;
           if (i <= 1) 
		   {
			  dig = 0;
		   }
		   else
		   {
			  dig = 11 - i;
		   }
        }
        return (dig == parseInt(ie.charAt(8)));
        break;
   
   case "AP":

        if (ie.length != 9)
           return false;
		if (ie.substring(0,2) != "03")
		   return false;
        var p = 0, d = 0, i = ie.substring(1,8);
        if ((i >= 3000001) && (i <= 3017000))
        {
           p =5;
           d = 0;
        }
        else if ((i >= 3017001) && (i <= 3019022))
        {
           p = 9;
           d = 1;
        }
        b = 9;
        soma = p;
        for (var i=0; i<=7; i++)
        {
            soma += parseInt(ie.charAt(i)) * b;
            b--;
        }
        dig = 11 - (soma % 11);
        if (dig == 10)
        {
           dig = 0;
        }
        else if (dig == 11)
        {
           dig = d;
        }
        return (dig == parseInt(ie.charAt(8)));
        break;
   
   case "BA":
   
        if (ie.length == 8)
		{
           die = ie.substring(0, 8);
           var nro = new Array(8);
           var dig = -1;
           for (var i=0; i<=7; i++)
               nro[i] = parseInt(die.charAt(i));
           var NumMod = 0;
           if (String(nro[0]).match(/[0123458]/))
	       {
              NumMod = 10;
		   }
           else
		   {
              NumMod = 11;
		   }
		   b = 7;
           soma = 0;
           for (i=0; i<=5; i++)
           {
               soma += nro[i] * b;
               b--;
           }
           i = soma % NumMod;
           if (NumMod == 10)
           {
              if (i == 0) { dig = 0; } else { dig = NumMod - i; }
           }
           else
           {
              if (i <= 1) { dig = 0; } else { dig = NumMod - i; }
           }
           resultado = (dig == nro[7]);
           if (!resultado)
	          return false;
           b = 8;
           soma = 0;
           for (i=0; i<=5; i++)
           {
               soma += nro[i] * b;
               b--;
           }
           soma += nro[7] * 2;
           i = soma % NumMod;
           if (NumMod == 10)
           {
              if (i == 0) { dig = 0; } else { dig = NumMod - i; }
           }
           else
           {
              if (i <= 1) { dig = 0; } else { dig = NumMod - i; }
           }
           return (dig == nro[6]);
		}

        if (ie.length == 9)
		{
           die = ie.substring(0, 9);
           var nro = new Array(9);
           var dig = -1;
           for (var i=0; i<=8; i++)
               nro[i] = parseInt(die.charAt(i));
           var NumMod = 0;
           if (String(nro[0]).match(/[0123458]/))
           {
              NumMod = 10;
		   }
           else
	       {
              NumMod = 11;
	       }
	       b = 8;
           soma = 0;
           for (i=0; i<=6; i++)
           {
               soma += nro[i] * b;
               b--;
           }
           i = soma % NumMod;
           if (NumMod == 10)
           {
              if (i == 0) { dig = 0; } else { dig = NumMod - i; }
           }
           else
           {
              if (i <= 1) { dig = 0; } else { dig = NumMod - i; }
           }
           resultado = (dig == nro[8]);
           if (!resultado)
              return false;
           b = 9;
           soma = 0;
           for (i=0; i<=6; i++)
           {
               soma += nro[i] * b;
               b--;
           }  
           soma += nro[8] * 2;
           i = soma % NumMod;
           if (NumMod == 10)
           {
              if (i == 0) { dig = 0; } else { dig = NumMod - i; }
           }
           else
           {
              if (i <= 1) { dig = 0; } else { dig = NumMod - i; }
           }
           return (dig == nro[7]);
		}

		return false;
		break;

   case "CE":
   
        if (ie.length != 9)
           return false;
		die = ie;
        var nro = Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(die[i]);
        b = 9;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;
        }
        dig = 11 - (soma % 11);
        if (dig >= 10)
           dig = 0;
        return (dig == nro[8]);
        break;

   case "DF":
   
        if (ie.length != 13)
           return false;
        var nro = new Array(13);
        for (var i=0; i<=12; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 4;
        soma = 0;
        for (i=0; i<=10; i++)
        {
            soma += nro[i] * b;
            b--;
            if (b == 1)
               b = 9;
        }
        dig = 11 - (soma % 11);
        if (dig >= 10)
           dig = 0;
        if (dig != nro[11])
           return false;  
        b = 5;
        soma = 0;
        for (i=0; i<=11; i++)
        {
            soma += nro[ i ] * b;
            b--;
            if (b == 1)
               b = 9;
        }
        dig = 11 - (soma % 11);
        if (dig >= 10)
           dig = 0;
        return (dig == nro[12]);
        break;
   
   case "ES":

        if (ie.length != 9)
           return false;
        var nro = new Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 9;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;
        }
        i = soma % 11;
        if (i < 2) { dig = 0; } else { dig = 11 - i; }
        return (dig == nro[8]);
        break;

   case "GO":
   
        if (ie.length != 9)
           return false;
        s = ie.substring(0, 2);
        if ((s == '10') || (s == '11') || (s == '15'))
        {
           var nro = new Array(9);
           for (var i=0; i<=8; i++)
               nro[i] = parseInt(ie.charAt(i));
           //n = Math.floor(ie / 10);
           n = parseInt(ie.substring(0, 7));
           if (n = 11094402)
           {
              if ((nro[8] == 0) || (nro[8] == 1))
                 return true;
           }
           b = 9;
           soma = 0;
           for (i=0; i<=7; i++)
           {
               soma += nro[i] * b;
               b--;
           }
           i = soma % 11;
           if (i == 0)
              dig = 0;
           else
           {
              if (i == 1)
              {
                  if ((n >= 10103105) && (n <= 10119997))
                     dig = 1;
                  else
                     dig = 0;
              }
              else
                  dig = 11 - i;
           }
           return (dig == nro[8]);
        }
        return false;
        break;

   case "MA":

        if (ie.length != 9)
           return false;
        if ( ie.substring(0, 2) != "12" )
		   return false;
        var nro = new Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 9;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;
        }
        i = soma % 11;
        if (i <= 1) { dig = 0; } else { dig = 11 - i; }
        return (dig == nro[8]);
        break;

   case "MG":
   
        if (ie.length != 13)
           return false;
        dig1 = ie.substring(11, 12);
        dig2 = ie.substring(12, 13);
        inscC = ie.substring(0, 3) + '0' + ie.substring(3, 11);
        insc = inscC.split('');
        npos = 11;
        i = 1;
        ptotal = 0;
        psoma = 0;
        while (npos >= 0)
        {
              i++;
              psoma = parseInt(insc[npos]) * i;
              if (psoma >= 10)
                 psoma -= 9;
              ptotal += psoma;
              if (i == 2)
                 i = 0;
              npos--;
        }
        nresto = ptotal % 10;
        if (nresto == 0)
           nresto = 10;
        nresto = 10 - nresto;
        if (nresto != parseInt(dig1))
           return false;
        npos = 11;
        i = 1;
        ptotal = 0;
        is=ie.split('');
        while (npos >= 0)
        {
              i++;
              if (i == 12)
                 i = 2;
              ptotal += parseInt(is[npos]) * i;
              npos--;
        }
        nresto = ptotal % 11;
        if ((nresto == 0) || (nresto == 1))
           nresto = 11;
        nresto = 11 - nresto;  
        return (nresto == parseInt(dig2));
		break;
  
   case "MS":
   
        if (ie.length != 9)
           return false;
        if (ie.substring(0,2) != "28")
           return false;
        var nro = new Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 9;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;
        }
        i = soma % 11;
        if (i <= 1) { dig = 0; } else { dig = 11 - i; }
        return (dig == nro[8]);
        break;

   case "MT":
   
        if (ie.length != 11)
           return false;
        die = ie;
        var nro = new Array(11);
        for (var i=0; i<=10; i++)
            nro[i] = parseInt(die[i]);
        b = 3;
        soma = 0;
        for (i=0; i<=9; i++)
        {
            soma += nro[i] * b;
            b--;
            if (b == 1)
               b = 9;
        }
        i = soma % 11;
        if (i <= 1) { dig = 0; } else { dig = 11 - i; }
        return (dig == nro[10]);
        break;

   case "PA":

        if (ie.length != 9)
           return false;
        if (ie.substring(0, 2) != '15')
           return false;
        var nro = new Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 9;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;
        }
        i = soma % 11;
        if (i <= 1)
           dig = 0;
        else
           dig = 11 - i;
        return (dig == nro[8]);
        break;

   case "PB":
   
        if (ie.length != 9)
           return false;
        var nro = new Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 9;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;  
        }
        i = soma % 11;
        if (i <= 1)
           dig = 0;
        else
           dig = 11 - i;
        return (dig == nro[8]);
        break;

   case "PE":

        // IE antiga com 14 digitos
        if (ie.length == 14)
        {
           var nro = new Array(14);
           for (var i=0; i<=13; i++)
               nro[i] = parseInt(ie.charAt(i));
           b = 5;
           soma = 0;
           for (i=0; i<=12; i++)
           {
               soma += nro[i] * b;
               b--;
               if (b == 0)
                  b = 9;
           }
           dig = 11 - (soma % 11);
           if (dig > 9)
              dig = dig - 10;
           return (dig == nro[13]);
		}

        // IE nova com 9 digitos
        if (ie.length == 9)
        { 
		   var nro = new Array(9);
           for (var i=0; i<=8; i++)
               nro[i] = parseInt(ie.charAt(i));
           b = 8;
           soma = 0;
           for (i=0; i<=6; i++)
           {
               soma += nro[i] * b;
               b--;
           }
           i = soma % 11;
           if (i <= 1) { dig = 0; } else { dig = 11 - i; }
           if (dig != nro[7])
              return false;
           b = 9;
           soma = 0;
           for (i=0; i<=7; i++)
           {
               soma += nro[i] * b;
               b--;
           }
           i = soma % 11;
           if (i <= 1) { dig = 0; } else { dig = 11 - i; }
           return (dig == nro[8]);
		}
		
		return false;
		break;
		
   case "PI":
   
        if (ie.length != 9)
           return false;
        var nro = new Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 9;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;
        }
        i = soma % 11;
        if (i <= 1) { dig = 0; } else { dig = 11 - i; }
        return (dig == nro[8]);
        break;

   case "PR":
   
        if (ie.length != 10)
           return false;
        var nro = new Array(10);
        for (var i=0; i<=9; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 3;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;
            if (b == 1)
               b = 7;
        }
        i = soma % 11;
        if (i <= 1)
           dig = 0;
        else
           dig = 11 - i;
        if (dig != nro[8])
           return false;
        b = 4;
        soma = 0;
        for (i=0; i<=8; i++)
        {
            soma += nro[i] * b;
            b--;
            if (b == 1)
               b = 7;
        }
        i = soma % 11;
        if (i <= 1)
           dig = 0;
        else
           dig = 11 - i;
        return (dig == nro[9]);
        break;

   case "RJ":
   
        if (ie.length != 8)
           return false;
        var nro = new Array(8);
        for (var i=0; i<=7; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 2;
        soma = 0;
        for (i=0; i<=6; i++)
        {
            soma += nro[i] * b;
            b--;
            if (b == 1)
               b = 7;
        }
        i = soma % 11;
        if (i <= 1) { dig = 0; } else { dig = 11 - i; }
        return (dig == nro[7]);
        break;

   case "RN":

        if (ie.substring(0, 2) != '20')
           return false;

        // IE com 9 digitos
		if (ie.length == 9)
        {
           var nro = new Array(9);
           for (var i=0; i<=8; i++)
               nro[i] = parseInt(ie.charAt(i));
           b = 9;
           soma = 0;
           for (i=0; i<=7; i++)
           {
               soma += nro[i] * b;
               b--;
           }
           soma *= 10;
           dig = soma % 11;
           if (dig == 10)
              dig = 0;
           return (dig == nro[8]);
		}

        // IE com 10 digitos
        if (ie.length == 10)
        {
           var nro = new Array(10);
           for (var i=0; i<=9; i++)
               nro[i] = parseInt(ie.charAt(i));
           b = 10;
           soma = 0;
           for (i=0; i<=8; i++)
           {
               soma += nro[i] * b;
               b--;
           }
           soma *= 10;
           dig = soma % 11;
           if (dig == 10)
              dig = 0;
           return (dig == nro[9]);
		}

        return false;
		break;

   case "RO":

        if (ie.length != 14)
           return false;
        var nro = new Array(14);
        b=6;
        soma=0;
        for (var i=0; i <= 12; i++)
		{
            nro[i] = parseInt(ie.charAt(i));
            soma += nro[i] * b;
            b--;
            if (b == 1)
               b = 9;
        }
        dig = 11 - ( soma % 11);
        if (dig >= 10)
           dig = dig - 10;
        return (dig == parseInt(ie.charAt(13)));
        break;

   case "RR":

        if (ie.length != 9)
           return false;
        if (ie.substring(0,2) != "24")
           return false;
        var nro = new Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(ie.charAt(i));
        var soma = 0;
        var n = 0;
        for (i=0; i<=7; i++)
            soma += nro[ i ] * ++n;
        dig = soma % 9;
        return (dig == nro[8]);
        break;

   case "RS":

        if (ie.length != 10)
           return false;
        var nro = new Array(10);
        for (var i=0; i<=9; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 2;
        soma = 0;
        for (i=0; i<=8; i++)
        {
            soma += nro[i] * b;
            b--;
            if (b == 1)
                b = 9;
        }
        dig = 11 - (soma % 11);
        if (dig >= 10)
           dig = 0;
        return (dig == nro[9]);
        break;

   case "SC":
 
        if (ie.length != 9)
           return false;
        var nro = new Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 9;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;
        }
        i = soma % 11;
        if (i <= 1)
           dig = 0;
        else
           dig = 11 - i;
        return (dig == nro[8]);
        break;

   case "SE":

        if (ie.length != 9)
           return false;
        var nro = new Array(9);
        for (var i=0; i<=8; i++)
            nro[i] = parseInt(ie.charAt(i));
        b = 9;
        soma = 0;
        for (i=0; i<=7; i++)
        {
            soma += nro[i] * b;
            b--;
        }
        dig = 11 - (soma % 11);
        if (dig >= 10)
           dig = 0;
        return (dig == nro[8]);
        break;
		
   case "SP":

        if (ie.length != 12)
           return false;
        var nro = new Array(12);
        for (var i=0; i<=11; i++)
	        nro[i] = parseInt(ie.charAt(i));
        soma = (nro[0] * 1) + (nro[1] * 3) + (nro[2] * 4) + (nro[3] * 5) + (nro[4] * 6) + (nro[5] * 7) + (nro[6] * 8) + (nro[7] * 10);
        dig = soma % 11;
        if (dig >= 10)
	       dig = 0;
        if (dig != nro[8])
           return false;
        soma = (nro[0] * 3) + (nro[1] * 2) + (nro[2] * 10) + (nro[3] * 9) + (nro[4] * 8) + (nro[5] * 7) + (nro[6] * 6)  + (nro[7] * 5) + (nro[8] * 4) + (nro[9] * 3) + (nro[10] * 2);
        dig = soma % 11;
        if (dig >= 10)
	       dig = 0;
        return (dig == nro[11]);
        break;

   case "TO":

        if (ie.length != 11)
           return false;
		s = ie.substring(2,4);
        if ((s != "01") && (s != "02") && (s != "03") && (s != "99")) 
		   return false;
		var nro = new Array(11);
        b=9;
        soma=0;
        for (var i=0; i<=9; i++)
        {
            nro[i] = parseInt(ie.charAt(i));
            if( i != 2 && i != 3)
			{
               soma += nro[i] * b;
               b--;
            }
        }
        resto = soma % 11;
        if ( resto < 2 ) { dig = 0; } else { dig = 11 - resto; }
        return (dig == parseInt(ie.charAt(10)));
        break;
   
   default:
        return false;
		
   }
}

</script>

<style>
	.fieldset > .field:not(.choice) > .label {
		padding: 6px 15px 0 0;
		text-align: left;
		width: 100%;
		box-sizing: border-box;
		float: left;
	}
	.cont_check_mm .control {
		margin: 0 0 20px;
		width: 74.2%;
	}
	.field.choice.newsletter {
		float: left;
		width: 100%;
	}
</style>