<?php
/**
 * @category   Commcenter
 * @package    Commcenter_Preregistro
 * @author     yurirneves@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Commcenter\Preregistro\Model\ResourceModel;

class Preregistro extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('commcenter_preregistro', 'preregistro_id');   //here "commcenter_preregistro" is table name and "preregistro_id" is the primary key of custom table
    }
}