<?php
$googleTagManagerStatus = $this->getGoogleTagManagerStatus();
$sessionId = $this->getSessionId();
$appName = $this->getAppName();

if($googleTagManagerStatus):
?>
    <input type="hidden" id="magento_sessionID" value="<?php echo $sessionId; ?>" />
    <script type="text/javascript">
        jQuery(document).ready(function  () {
            (function (a, b, c, d, e, f, g) {
            a['CsdpObject'] = e; a[e] = a[e] || function () {
            (a[e].q = a[e].q || []).push(arguments)
            }, a[e].l = 1 * new Date(); f = b.createElement(c),
            g = b.getElementsByTagName(c)[0]; f.async = 1; f.src = d; g.parentNode.insertBefore(f, g)
            })(window, document, 'script', '//device.clearsale.com.br/p/fp.js', 'csdp');
            csdp('app', '<?php echo $appName ?>');
            csdp('inputsessionid', "magento_sessionID");
        })
    </script>
<?php
else :
?>
    <script type="text/javascript">
        (function (a, b, c, d, e, f, g) {
        a['CsdpObject'] = e; a[e] = a[e] || function () {
        (a[e].q = a[e].q || []).push(arguments)
        }, a[e].l = 1 * new Date(); f = b.createElement(c),
        g = b.getElementsByTagName(c)[0]; f.async = 1; f.src = d; g.parentNode.insertBefore(f, g)
        })(window, document, 'script', '//device.clearsale.com.br/p/fp.js', 'csdp');
        csdp('app', '<?php echo $appName ?>');
        csdp('sessionid', '<?php echo $sessionId ?>');
    </script>
    <?php
endif; 