<?php
/** @var $block \Magento\Catalog\Block\Product\View */
$_product = $block->getProduct();
$attributes = $_product->getAttributes();

$filteredAttributes = [];

if ($attributes) {
    foreach ($attributes as $attribute) {
        $attributeModel = $_product->getResource()->getAttribute($attribute->getAttributeCode());

        if ($attributeModel && $attributeModel->getData('show_in_technical_sheet') == 1) {
            $value = $attribute->getFrontend()->getValue($_product);

            if ($value) {
                $filteredAttributes[] = [
                    'label' => $block->escapeHtml($attribute->getStoreLabel()),
                    'value' => $value,
                ];
            }
        }
    }
}
?>

<?php
/** 
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Catalog\Model\Product $_product 
 */
?>

<?php $_product = $block->getProduct(); ?>

<?php if ($_product->getShortDescription()): ?>
    <div class="product-short-description sheets">
        <div class="title-description">
            <h3>Informações do produto</h3>

            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="9" viewBox="0 0 14 9" fill="none">
                <path d="M1.66666 1.8335L6.99999 7.16683L12.3333 1.8335" stroke="#323232" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </div>
        
        <div class="content-wrapper">
            <div class="content-description ">
                <?php if (!empty($filteredAttributes)): ?>
                    <div class="technical-sheets">
                        <ul class="box-sheets">
                            <?php foreach ($filteredAttributes as $attr): ?>
                                <li class="item-sheets">
                                    <p class="label-sheets"><?php echo $attr['label'] ?></p>
                                    <p class="value-sheets"><?php echo $attr['value'] ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
            </div>

            <div class="load-more">
                <p>
                    <span class="load-more-text">Ver mais</span>

                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="25" viewBox="0 0 24 25" fill="none">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M3.11799 12.967C2.96099 12.676 2.96099 12.323 3.11799 12.032C5.00999 8.533 8.50499 5.5 12 5.5C15.495 5.5 18.99 8.533 20.882 12.033C21.039 12.324 21.039 12.677 20.882 12.968C18.99 16.467 15.495 19.5 12 19.5C8.50499 19.5 5.00999 16.467 3.11799 12.967Z" stroke="#14B449" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M14.1213 10.3787C15.2929 11.5502 15.2929 13.4497 14.1213 14.6213C12.9497 15.7929 11.0502 15.7929 9.87868 14.6213C8.70711 13.4497 8.70711 11.5502 9.87868 10.3787C11.0502 9.20711 12.9497 9.20711 14.1213 10.3787" stroke="#14B449" stroke-width="1.4286" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </p>
            </div>
        </div>
    </div>
<?php endif; ?>