<div  data-area-active="true">
    <div class="fieldset-wrapper"  data-level="0" data-index="customer">


        <div class="fieldset-wrapper-title"  tabindex="-1">

            <strong  class="title">
                <span >Inclusão de pedido </span>
            </strong>
        </div>

        <div class="admin__fieldset-wrapper-content _hide" >
            <fieldset class="admin__fieldset" >
                <div class="admin__field _required _disabled"  data-index="website_id">


<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$order_id = $this->getRequest()->getParam('order_id');
$order = $objectManager->create('\Magento\Sales\Model\Order')->load($order_id);
$additionalInformation = $order->getPayment()->getAdditionalInformation();
$sigep_nota_fiscal = '';
$sigep_valor_declarado = '';
if(isset($additionalInformation['sigep_nota_fiscal']) && $additionalInformation['sigep_valor_declarado']){
    $sigep_nota_fiscal = $additionalInformation['sigep_nota_fiscal'];
    $sigep_valor_declarado = $additionalInformation['sigep_valor_declarado'];
}
?>



<div class="admin__field"  data-index="prefix">
    <div class="admin__field-label" ><label  for="nota_fiscal"><span >Nota fiscal:</span></label></div>
    <div class="admin__field-control" ><input class="admin__control-text" type="text" value="<?=$sigep_nota_fiscal?>"  id="nota_fiscal" maxlength="255"></div>
</div>

<div class="admin__field"  data-index="prefix">
    <div class="admin__field-label" ><label  for="valor_declarado"><span >Valor declarado:</span></label></div>
    <div class="admin__field-control" ><input class="admin__control-text" value="<?=$sigep_valor_declarado?>"  type="text"  aria-describedby="notice-Y9TU3HU" id="valor_declarado" maxlength="255"></div>
</div>


    <button type="submit" onclick="sendInfoSigepWeb()" class="btn btn-primary">Enviar</button>




<script>
    var order_id = "<?=$order_id?>";
    function sendInfoSigepWeb() {
        var valor_declarado = document.getElementById('valor_declarado').value;
        var nota_fiscal = document.getElementById('nota_fiscal').value;


        if(valor_declarado && nota_fiscal){
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    alert(this.responseText);
                    location.reload();
                }
            };

            xmlhttp.open("GET", "<?=$baseUrl?>mestremage/pdf?param=set_infos&valor_declarado=" + valor_declarado+'&nota_fiscal='+nota_fiscal+'&order_id=<?=$order_id?>', true);
            xmlhttp.send();
        }else{
            alert('Preecha todos os campos');
        }


    }
</script>



        </div>
    </fieldset>
    </div>
    </div>
</div>
<style>
    .admin__field-control .admin__control-text {
        width: 30%;
        margin-left: 10px;
    }
    .admin__field:not(.admin__field-option) > .admin__field-label {
        float: left;
        margin-left: 40px;
        width: 208px;
        text-align: left;
    }
    div#Pedido_SigepWeb button.btn.btn-primary {
        margin: 21px 44%;
        display: flex;
    }
    div#Pedido_SigepWeb  select {
        -webkit-appearance: none;
        background-color: #ffffff;
        border: 1px solid #adadad;
        border-radius: 1px;
        box-shadow: none;
        color: #303030;
        font-size: 1.4rem;
        font-weight: 400;
        height: auto;
        line-height: 1.36;
        padding: 0.6rem 1rem 0.6rem;
        transition: border-color 0.1s linear;
        vertical-align: baseline;
        margin-left: 10px;
    }

</style>