
<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$order = $objectManager->create('Magento\Sales\Model\Order')->load($this->getRequest()->getParam('order_id'));
$scopeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');


$trackNumbers = '';
$tracksCollection = $order->getTracksCollection();
foreach ($tracksCollection->getItems() as $track) {
    $trackNumbers = $track->getTrackNumber();
}
$html = '';
    if ($trackNumbers) {
        $html = '<div class="block block-order-tracking-view"><div class="block-title"><strong>'.$scopeConfig->getValue('carriers/correios/name', $storeScope).'</strong></div><div class="block-content">';
        $tracking = (array)\MestreMage\Correios\Model\Carrier\Correios::getTrackingInfoByCode($trackNumbers);
        if (isset($tracking['success'])) {
            foreach($tracking as $item){
                if (isset($item['message']) && !empty($item['message'])) {
                    $html .= '<div class="tracking-mm">';
                    $html .= '<p>'.(isset($item['date']) ? $item['date'] : '') .' '.(isset($item['hour']) ? $item['hour'] : '').' | '.(isset($item['location']) ? $item['location'] : '').'</p>';
                    $html .= '<h3>'. $item['message'].'</h3>';
                    $html .= '</div>';
                }
            }
        }
        $html .= '</div></div>';
    }
?>
<style>
.tracking-mm h3 {
    padding-bottom: 8px;
    margin: 0 0 30px 0;
    border-bottom: 1px solid #ebebeb;
}
</style>
<script>
    document.querySelector('.block.block-order-details-view').insertAdjacentHTML('beforebegin', '<?=$html?>');
</script>