<?php

/**
 * @var $block \MestreMage\AutoCompleteZipCode\Block\AutoCompleteZipCode
 */
?>

<?php if ($block->isActiv()) :
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$scopeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
	$mask_postcode = $scopeConfig->getValue('autocompletezipcode/geral/mask_postcode', \Magento\Store\Model\ScopeInterface::SCOPE_STORES);
	$getAllRegions = $objectManager->create('\MestreMage\AutoCompleteZipCode\Helper\Data')->getAllRegions();

?>
	<style>
		.field._required label.label:after {
			content: '*';
			color: #e02b27;
			font-size: 1.2rem;
			margin: 0 0 0 5px;
		}
	</style>

	<script>
		var get_all_regions = JSON.parse('<?= json_encode($getAllRegions) ?>');
		var is_mask_postcode = '<?= $mask_postcode ?>';
		var tipo_formulario = '';
		require(['jquery', 'jquery/ui'], function($) {

			$(document).ready(function() {
				var existCondition = setInterval(function() {
					var postcod = $('.form-shipping-address [name*="postcode"]:nth-child(1)');

					if (postcod.val()) {
						pesquisacepIw3(postcod.val());
					}

					if (postcod.length) {
						clearInterval(existCondition);
						postcod.keyup(function() {
							$(this).val(maskCep($(this).val()));
						});

						postcod.attr('inputmode', 'numeric');
						postcod.on('change input', function() {
							if ($(this).val().length >= (8 + parseInt(is_mask_postcode))) {
								$('.form-shipping-address [name*="country_id"]').val('BR');
								tipo_formulario = '.form-shipping-address';
								pesquisacepIw3(postcod.val());
								console.log(postcod.val());

								$('.form-shipping-address [name*="country_id"]').trigger('change');
							}
						});
					}
				}, 100);

				var existCondition2 = setInterval(function() {
					var postcod = $('.billing-address-form [name*="postcode"]:nth-child(1)');
					if (postcod.length) {
						clearInterval(existCondition2);
						postcod.keyup(function() {
							$(this).val(maskCep($(this).val()));
						});
						postcod.change(function() {
							$('.billing-address-form [name*="country_id"]').val('BR');
							tipo_formulario = '.billing-address-form';
							pesquisacepIw3($(this).val());

							console.log($(this).val());


							$('.billing-address-form [name*="country_id"]').trigger('change');
						});
					}
				}, 100);

				var Intervaltel = setInterval(function() {
					var telephone = $('.form-shipping-address [name*="telephone"]:nth-child(1)');
					var fax = $('.form-shipping-address [name*="fax"]:nth-child(1)');
					if (telephone.length) {
						clearInterval(Intervaltel);
						telephone.keyup(function() {
							$(this).val(maskTel($(this).val()));
						});
						fax.keyup(function() {
							$(this).val(maskTel($(this).val()));
						});
					}
				}, 1000);

				var Intervaltelbilling = setInterval(function() {
					var telephonebilling = $('.billing-address-form [name*="telephone"]:nth-child(1)');
					if (telephonebilling.length) {
						clearInterval(Intervaltelbilling);
						telephonebilling.keyup(function() {
							$(this).val(maskTel($(this).val()));
						});
					}
				}, 1000);

			});
		});

		function maskTel(v) {
			if (v.length > 15) {
				return v.substring(0, 15);
			}
			v = v.replace(/\D/g, "");
			v = v.replace(/^(\d{2})(\d)/g, "($1) $2");
			v = v.replace(/(\d)(\d{4})$/, "$1-$2");
			return v;
		}

		function maskCep(v) {
			if (is_mask_postcode != '1') {
				return v
			}

			if (v.length > 9) {
				return v.substring(0, 9);
			}
			v = v.replace(/\D/g, "");
			v = v.replace(/^(\d{5})(\d)/, "$1-$2");
			return v
		}

		function limpa_formulario_cep() {
			jQuery(tipo_formulario + ' [name*="street[0]"]').val("");
			jQuery(tipo_formulario + ' [name*="street[3]"]').val("");
			jQuery(tipo_formulario + ' [name*="city"]').val("");
			jQuery(tipo_formulario + ' [name*="region_id"]').val("");

			jQuery(tipo_formulario + ' [name*="street[0]"]').prop('disabled', false);
			jQuery(tipo_formulario + ' [name*="street[3]"]').prop('disabled', false);
			jQuery(tipo_formulario + ' [name*="city"]').prop('disabled', false);
			jQuery(tipo_formulario + ' [name*="region_id"]').prop('disabled', false);
			jQuery(tipo_formulario + ' [name*="country"]').prop('disabled', false);
		}

		function retornoApi(conteudo) {
			if (!("erro" in conteudo)) {

				if (conteudo.logradouro){
					jQuery(tipo_formulario + ' [name*="street[0]"]').val(conteudo.logradouro);
					jQuery(tipo_formulario + ' [name*="street[0]"]').prop('disabled', true);
					jQuery(tipo_formulario + ' [name*="street[1]"]').focus();
				} else {
					jQuery(tipo_formulario + ' [name*="street[0]"]').prop('disabled', false);
					jQuery(tipo_formulario + ' [name*="street[0]"]').val("");
				}
				
				if (conteudo.bairro){
					jQuery(tipo_formulario + ' [name*="street[3]"]').val(conteudo.bairro);
					jQuery(tipo_formulario + ' [name*="street[3]"]').prop('disabled', true);
				} else {
					jQuery(tipo_formulario + ' [name*="street[3]"]').prop('disabled', false);
					jQuery(tipo_formulario + ' [name*="street[3]"]').val("");
				}
				
				if (conteudo.localidade){
					jQuery(tipo_formulario + ' [name*="city"]').val(conteudo.localidade);
					jQuery(tipo_formulario + ' [name*="city"]').prop('disabled', true);
				} else {
					jQuery(tipo_formulario + ' [name*="city"]').prop('disabled', false);
					jQuery(tipo_formulario + ' [name*="city"]').val("");
				}
				
				if (conteudo.uf){
					jQuery(tipo_formulario + ' [name*="regiao-uf"]').prop('disabled', true);
					jQuery(tipo_formulario + ' [name*="region_id"]').prop('disabled', true);
					jQuery(tipo_formulario + ' [name*="country"]').prop('disabled', true);
				} else {
					jQuery(tipo_formulario + ' [name*="regiao-uf"]').prop('disabled', false);
					jQuery(tipo_formulario + ' [name*="region_id"]').prop('disabled', false);
					jQuery(tipo_formulario + ' [name*="country"]').prop('disabled', false);
					jQuery(tipo_formulario + ' [name*="regiao-uf"]').val("");
					jQuery(tipo_formulario + ' [name*="region_id"]').val("");
					jQuery(tipo_formulario + ' [name*="country"]').val("");
				}

				var region_id = jQuery(tipo_formulario + ' [name*="region_id"]');

				if (region_id.attr('type') == 'text') {
					region_id.val(conteudo.localidade);
				} else {
					region_id.val(setUf(conteudo.uf));
				}
				jQuery(tipo_formulario + ' [name*="street[0]"]').trigger('keyup');
				jQuery(tipo_formulario + ' [name*="street[3]"]').trigger('keyup');
				jQuery(tipo_formulario + ' [name*="city"]').trigger('keyup');
				jQuery(tipo_formulario + ' [name*="region_id"]').trigger('change');


				var complemento = jQuery(tipo_formulario + ' [name*="street[2]"]');
				if (!complemento.val()) {
					!complemento.val('...');
					!complemento.trigger('keyup');
				}

			} else {
				limpa_formulario_cep();
			}
		}

		//ao digitar todos os 8 digitos
		const inputCep = document.getElementById('zip');
		inputCep.addEventListener('input', function() {
			
			jQuery(tipo_formulario + ' [name*="street[0]"]').prop('disabled', false);
			jQuery(tipo_formulario + ' [name*="street[3]"]').prop('disabled', false);
			jQuery(tipo_formulario + ' [name*="city"]').prop('disabled', false);
			jQuery(tipo_formulario + ' [name*="region_id"]').prop('disabled', false);
			jQuery(tipo_formulario + ' [name*="country"]').prop('disabled', false);
			
			let inputCep2 = document.getElementById('zip').value.replace(/-/g, "");
			if (inputCep2.length === 8) {
				inputCep.blur();
				jQuery(tipo_formulario + ' [name*="street[0]"]').focus();
			}
		});

		function pesquisacepIw3(valor) {
			var cep = valor.replace(/\D/g, '');
			if (cep != "") {
				var validacep = /^[0-9]{8}$/;
				if (validacep.test(cep)) {
					var script = document.createElement('script');
					script.src = '//viacep.com.br/ws/' + cep + '/json/?callback=retornoApi';
					document.body.appendChild(script);

				} else {
					limpa_formulario_cep();
				}
			} else {
				limpa_formulario_cep();
			}

		};

		function getObjects(obj, key, val) {
			var objects = [];
			for (var i in obj) {
				if (!obj.hasOwnProperty(i)) continue;
				if (typeof obj[i] == 'object') {
					objects = objects.concat(getObjects(obj[i], key, val));
				} else
				if (i == key && obj[i] == val || i == key && val == '') {
					objects.push(obj);
				} else if (obj[i] == val && key == '') {
					if (objects.lastIndexOf(obj) == -1) {
						objects.push(obj);
					}
				}
			}
			return objects;
		}

		function setUf(uf) {
			let id = getObjects(get_all_regions, 'code', uf);
			return id[0].id;
		}
	</script>
<?php endif; ?>