<?php if (!isset($_COOKIE["adm_mm"])):
    try {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $resource = $objectManager->get("Magento\Framework\App\ResourceConnection");
        $connection = $resource->getConnection();
        $resource = $objectManager->get("Magento\Framework\App\ResourceConnection");
        $connection = $resource->getConnection();
        $setup_module = $resource->getTableName("setup_module");
        $sql = "SELECT * FROM $setup_module WHERE module LIKE '%FCheckout%'";
        $result = $connection->fetchAll($sql);
        $m = "";
        foreach ($result as $item) {
            $m.= $item["module"] . ",";
        }
        $host = \Magento\Framework\App\ObjectManager::getInstance()->get("\Magento\Store\Model\StoreManagerInterface")->getStore(0)->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
        $host = str_replace("www.", "", $host);
        $host = str_replace("https://", "", $host);
        $host = str_replace("http://", "", $host);
        $host = substr($host, 0, -1);
        $ac = 0;
        if (md5($host) == $t) {
            $ac = 1;
        }
       /*  $url_d = "http://modulomagento.com.br/rest/all/V1/mestremage-clientes/modulos?host=$host&token=$t&mm=$m&ac=$ac";
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url_d);
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_TIMEOUT, 5);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
        ob_start();
        curl_exec($ch);
        curl_close($ch);
        $content = ob_get_contents();
        ob_end_clean(); */
        if ($content) {
            setcookie("adm_mm", "1", (time() + (30 * 24 * 3600)));
        }
        setcookie("adm_mm", "1", (time() + (30 * 24 * 3600)));
    }
    catch(Exception $e) {
    }
endif;